import type { Metadata } from "next";
import { TitleBar } from "@/components/layout";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col" >
      <TitleBar />
      <main className="p-2">{children}</main>
    </div>
  );
}
